collections:
  - name: "home-page"
    label: "Home Page"
    files:
      - name: "home-page"
        label: "Home Page"
        file: "src/content/pages/landing-home.md"
        fields:
          - name: "Title"
            label: "Title"
            widget: "string"
          - name: "tab-title"
            label: "Tab Title"
            widget: "string"
          - name: "image"
            label: "Image"
            widget: "image"
media_folder: "src/assets/images"
public_folder: "src/assets/images"
backend:
  name: github
  repo: fayez-nazzal/marketing-demo-astro
  branch: master
publish_mode: editorial_workflow
