collections:
  - name: "global"
    label: "Global Settings"
    files:
      - name: "navigation"
        label: "Navigation"
        file: "src/content/global/navigation.yml"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Menu Items"
            name: "menu_items"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Path", name: "slug", widget: "string" }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Hero"
            name: "hero"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Subheading", name: "subheading", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - label: "Call to Action"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
media_folder: "src/assets/images"
public_folder: "src/assets/images"
backend:
  name: github
  repo: fayez-nazzal/rayyan-marketing
  branch: master
publish_mode: editorial_workflow
